import type { Store } from '@/types/store'

export const stores: Store[] = [
  {
    id: '1',
    name: 'Northside Market',
    ownerName: 'Alice Johnson',
    ownerEmail: 'alice@example.com',
    location: 'Seattle, WA',
    region: 'Northwest',
    phone: '+1 (206) 555-0148',
    productsCount: 218,
    currentOrders: 42,
    pendingOrders: 11,
    complaints: 2,
    status: 'Active',
  },
  {
    id: '2',
    name: 'Bayview Boutique',
    ownerName: 'Robert Tennison',
    ownerEmail: 'robert@example.com',
    location: 'San Francisco, CA',
    region: 'West Coast',
    phone: '+1 (415) 555-0199',
    productsCount: 154,
    currentOrders: 28,
    pendingOrders: 7,
    complaints: 4,
    status: 'Active',
  },
  {
    id: '3',
    name: 'Downtown Depot',
    ownerName: 'Bob White',
    ownerEmail: 'bob@example.com',
    location: 'Chicago, IL',
    region: 'Midwest',
    phone: '+1 (312) 555-0182',
    productsCount: 320,
    currentOrders: 61,
    pendingOrders: 15,
    complaints: 6,
    status: 'Paused',
  },
  {
    id: '4',
    name: 'Central Station',
    ownerName: 'Carol Doe',
    ownerEmail: 'carol@example.com',
    location: 'Atlanta, GA',
    region: 'Southeast',
    phone: '+1 (404) 555-0123',
    productsCount: 186,
    currentOrders: 19,
    pendingOrders: 4,
    complaints: 1,
    status: 'Active',
  },
  {
    id: '5',
    name: 'Lakeside Goods',
    ownerName: 'John Doe',
    ownerEmail: 'johndoe@example.com',
    location: 'Minneapolis, MN',
    region: 'Midwest',
    phone: '+1 (612) 555-0177',
    productsCount: 260,
    currentOrders: 35,
    pendingOrders: 9,
    complaints: 3,
    status: 'Pending',
  },
]

export function getStoreById(id: string): Store | undefined {
  return stores.find((store) => store.id === id)
}
